name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - master  # Trigger on push to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Hugo
      run: |
        HUGO_VERSION="0.139.2"  # Specify the version of Hugo
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        tar -xvzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        sudo mv hugo /usr/local/bin/hugo

    - name: Build Hugo Site
      run: |
        rm -rf public  # Clean previous builds if any
        cat hugo.toml
        hugo           # Build the Hugo site
        ls
        ls public      # List contents of the public folder for debugging
        echo a
        ls public/posts

    - name: Deploy to deploy Branch
      run: |
        cd public
        git init
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy site $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force "https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}" HEAD:deploy
